# Generated by Django 5.0.1 on 2024-01-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='isClosed',
            field=models.BooleanField(default=False),
        ),
    ]
