# Generated by Django 5.0.1 on 2024-02-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionlisting_winner_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='Category',
        ),
        migrations.AddField(
            model_name='categories',
            name='category',
            field=models.IntegerField(choices=[('Antiques', 'Antiques'), ('Art & Decor', 'Art'), ('Books', 'Books'), ('CD, DVD & Games', 'Games'), ('Clothing & Fasion', 'Clothing'), ('Collectables', 'Collectables'), ('Computers', 'Computers'), ('Dining', 'Dining'), ('Electronics & Gadgets', 'Electronics'), ('Handbags', 'Handbags'), ('Lawn & Garden', 'Lawn'), ('Sports & Equipment', 'Sports'), ('Toys', 'Toys'), ('Travel Accesaries', 'Travel')], null=True),
        ),
    ]
